spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/guns?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
logging:
  level:
      com:
        qiaoyanan:
           springbootplus:
              dao: debug
mybatis:
  type-aliases-package: com.qiaoyanan.springbootplus.model
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
